source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '~> 7.1.3', '>= 7.1.3.2'
gem 'sprockets-rails'
gem 'sqlite3', '~> 1.4'
gem 'activeadmin'
gem 'arbre'
gem 'devise'
gem 'nokogiri'
gem 'open-uri'
gem 'kaminari'
gem 'sassc-rails'
gem 'i18n'
gem 'puma', '>= 5.0'
gem 'importmap-rails'
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'jbuilder'
gem 'rss'
gem 'tzinfo-data', platforms: %i[windows jruby]
gem 'bootsnap', require: false

group :development, :test do
  gem 'letter_opener', '~> 1.7.0'
  gem 'capybara'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'selenium-webdriver'
end

group :development do
  gem 'web-console'
end

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
end
